include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: false
    always_declare_return_types: false

analyzer:
  language:
    strict-casts: true
  errors:
    invalid_annotation_target: ignore
